// Shared building blocks for hand-written (not zod-derived) OpenAI JSON
// Schemas - kept within the subset strict mode supports (no min/max
// length or item-count constraints). Used by both deckJsonSchema.ts
// (Phase 3, bulk generation) and tools.ts (Phase 4, tool-call arguments).

export const slideTypeEnumJsonSchema = {
  type: "string",
  enum: ["title", "content", "two-column", "comparison", "table"],
};

export const contentBlockArrayJsonSchema = {
  type: "array",
  items: {
    anyOf: [
      {
        type: "object",
        additionalProperties: false,
        properties: {
          type: { type: "string", enum: ["bullets"] },
          items: { type: "array", items: { type: "string" } },
          column: { type: ["integer", "null"], enum: [0, 1, null] },
        },
        required: ["type", "items", "column"],
      },
      {
        type: "object",
        additionalProperties: false,
        properties: {
          type: { type: "string", enum: ["paragraph"] },
          text: { type: "string" },
          column: { type: ["integer", "null"], enum: [0, 1, null] },
        },
        required: ["type", "text", "column"],
      },
      {
        type: "object",
        additionalProperties: false,
        properties: {
          type: { type: "string", enum: ["table"] },
          headers: { type: "array", items: { type: "string" } },
          rows: {
            type: "array",
            items: { type: "array", items: { type: "string" } },
          },
          column: { type: ["integer", "null"], enum: [0, 1, null] },
        },
        required: ["type", "headers", "rows", "column"],
      },
      {
        type: "object",
        additionalProperties: false,
        properties: {
          type: { type: "string", enum: ["chart"] },
          chartType: { type: "string", enum: ["bar", "line", "pie"] },
          data: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                label: { type: "string" },
                value: { type: "number" },
              },
              required: ["label", "value"],
            },
          },
          caption: { type: ["string", "null"] },
          column: { type: ["integer", "null"], enum: [0, 1, null] },
        },
        required: ["type", "chartType", "data", "caption", "column"],
      },
      {
        // No "url" here - the model never generates the actual image, only
        // describes what's wanted via "alt". lib/ai/generateImage.ts fills
        // url in asynchronously after the tool call / slide is applied.
        type: "object",
        additionalProperties: false,
        properties: {
          type: { type: "string", enum: ["image"] },
          alt: { type: "string" },
          caption: { type: ["string", "null"] },
          column: { type: ["integer", "null"], enum: [0, 1, null] },
        },
        required: ["type", "alt", "caption", "column"],
      },
    ],
  },
};

export const layoutHintsJsonSchema = {
  type: ["object", "null"],
  additionalProperties: false,
  properties: {
    align: {
      type: ["string", "null"],
      enum: ["left", "center", "right", null],
    },
    columns: { type: ["integer", "null"], enum: [1, 2, null] },
    columnTitles: { type: ["array", "null"], items: { type: "string" } },
    density: {
      type: ["string", "null"],
      enum: ["compact", "comfortable", "spacious", null],
    },
  },
  required: ["align", "columns", "columnTitles", "density"],
};

// A full slide's properties, minus "id" (assigned server/store-side, never
// generated by the model).
export const slidePropertiesJsonSchema = {
  type: slideTypeEnumJsonSchema,
  title: { type: "string" },
  subtitle: { type: ["string", "null"] },
  layout: layoutHintsJsonSchema,
  body: contentBlockArrayJsonSchema,
};

export const slideRequiredFields = [
  "type",
  "title",
  "subtitle",
  "layout",
  "body",
];
